// <auto-generated />
namespace PuffinNotes.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedNotemodelandchangedNoticeBoardmodeltouseboardIdaspk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedNotemodelandchangedNoticeBoardmodeltouseboardIdaspk));
        
        string IMigrationMetadata.Id
        {
            get { return "201301291852416_Added Note model and changed NoticeBoard model to use boardId as pk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
