// <auto-generated />
namespace PuffinNotes.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InitialSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201302071836515_InitialSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
