// <auto-generated />
namespace PuffinNotes.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addnotelisttonoticeboard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnotelisttonoticeboard));
        
        string IMigrationMetadata.Id
        {
            get { return "201302071832118_add note list to noticeboard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
